language: ruby
rvm:
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2.1.1
  - 1.8.7
before_install: "bundle config build.nokogiri --use-system-libraries"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database gdi_test;' -U postgres